spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: postgres
    password: 21092002
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true